#!/bin/bash
#SBATCH --job-name=unet_C0_128_convs_2
#SBATCH --partition=gpu_a100
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --gpus=1
#SBATCH --time=02:00:00
#SBATCH --mem=32G
#SBATCH --output=/home/scur0036/diffusion-models-project/logs/unet_C0_128_convs_2_%j.out
#SBATCH --error=/home/scur0036/diffusion-models-project/logs/unet_C0_128_convs_2_%j.err

echo "Job ID: $SLURM_JOB_ID"
echo "Node: $SLURMD_NODENAME"
echo "Start: $(date)"

source ~/.bashrc
conda activate diffusion

cd /home/scur0036/diffusion-models-project

python /home/scur0036/diffusion-models-project/cluster_train.py --model_path /home/scur0036/diffusion-models-project/models/unet_C0_128_convs_2/init.pt --train_dataset_path /home/scur0036/diffusion-models-project/models/unet_C0_128_convs_2/train_dataset.pt --test_dataset_path /home/scur0036/diffusion-models-project/models/unet_C0_128_convs_2/test_dataset.pt --epochs 300 --batch_size 32 --weight_decay 1e-06 --save_path /home/scur0036/diffusion-models-project/models/unet_C0_128_convs_2/trained.pkl --early_stopping 15

echo "Done: $(date)"
