#!/bin/bash
#SBATCH --job-name=vivien_unet_fashion
#SBATCH --partition=gpu_a100
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --gpus=1
#SBATCH --time=06:00:00
#SBATCH --mem=32G
#SBATCH --output=/home/scur0036/diffusion-models-project/logs/vivien_unet_fashion_%j.out
#SBATCH --error=/home/scur0036/diffusion-models-project/logs/vivien_unet_fashion_%j.err

echo "Job ID: $SLURM_JOB_ID"
echo "Node:   $SLURMD_NODENAME"
echo "Start:  $(date)"

source ~/.bashrc
conda activate diffusion

cd /home/scur0036/diffusion-models-project

python vivien/train_02_unet_fashion_mnist.py \
    --epochs 200 \
    --batch_size 128 \
    --lr 5e-5 \
    --n_timesteps 1000 \
    --timestep_emb_dim 256 \
    --dataset_path ~/datasets \
    --save_dir models/vivien_unet_fashion_mnist

echo "Done: $(date)"
